import { describe, it, expect } from "vitest";

import { parseDesignManifest } from "./designManifest";

const MANIFEST = [
  "# Design Manifest",
  "",
  "> Generated by shipwright-design | Profile: react-spa",
  "",
  "## Screens",
  "",
  "| # | Screen | File | Status | Linked FRs |",
  "|---|--------|------|--------|-----------|",
  "| 01 | dashboard | screens/01-dashboard.html | complete | FR-01.09 |",
  "| 02 | settings | screens/02-settings.html | complete | FR-01.10, FR-01.11 |",
  "| 03 | login | screens/03-login.html | complete |  |",
  "",
  "## User Flows",
  "",
  "| Flow | File | Status |",
  "|------|------|--------|",
  "| onboarding | flows/onboarding.html | complete |",
  "",
].join("\n");

describe("parseDesignManifest — the Screens table (A14, FR-01.58)", () => {
  // @covers FR-01.58
  it("parses each screen row: number, name, file, status, FRs", () => {
    const screens = parseDesignManifest(MANIFEST);
    expect(screens).toHaveLength(3);
    expect(screens[0]).toEqual({
      number: 1,
      name: "dashboard",
      file: "screens/01-dashboard.html",
      status: "complete",
      frs: ["FR-01.09"],
    });
  });

  // @covers FR-01.58
  it("parses multiple linked FRs in one cell, in order", () => {
    const screens = parseDesignManifest(MANIFEST);
    expect(screens[1].frs).toEqual(["FR-01.10", "FR-01.11"]);
  });

  // @covers FR-01.58
  it("keeps a screen whose FR cell is blank (FR dropped, never invented)", () => {
    const screens = parseDesignManifest(MANIFEST);
    expect(screens[2].name).toBe("login");
    expect(screens[2].frs).toEqual([]);
  });

  // @covers FR-01.58
  it("does NOT admit the User Flows rows as screens (only screens/*.html)", () => {
    const screens = parseDesignManifest(MANIFEST);
    expect(screens.every((s) => s.file.startsWith("screens/"))).toBe(true);
  });

  // @covers FR-01.58
  it("returns [] for the 'No screens generated yet.' placeholder", () => {
    const md = ["## Screens", "", "No screens generated yet.", ""].join("\n");
    expect(parseDesignManifest(md)).toEqual([]);
  });

  // @covers FR-01.58
  it("returns [] when there is no Screens section at all", () => {
    expect(parseDesignManifest("# Design Manifest\n\nnothing here")).toEqual([]);
  });

  // @covers FR-01.58
  it("returns [] for empty / non-string input (honest empty, never a throw)", () => {
    expect(parseDesignManifest("")).toEqual([]);
    // @ts-expect-error — defends the runtime guard against a non-string
    expect(parseDesignManifest(undefined)).toEqual([]);
  });

  // @covers FR-01.58
  it("keeps a numbered screen row with no servable file as a placeholder (file empty)", () => {
    const md = [
      "## Screens",
      "| # | Screen | File | Status | Linked FRs |",
      "|---|--------|------|--------|-----------|",
      "| 01 | ghost |  | complete | FR-01.01 |",
      "| 02 | real | screens/02-real.html | complete | |",
    ].join("\n");
    const screens = parseDesignManifest(md);
    expect(screens).toHaveLength(2);
    // The file-less row is preserved (metadata) but carries an empty file so the
    // gallery renders an honest "no preview file" placeholder, not a dead iframe.
    expect(screens[0]).toMatchObject({ name: "ghost", file: "", frs: ["FR-01.01"] });
    expect(screens[1]).toMatchObject({ name: "real", file: "screens/02-real.html" });
  });

  // @covers FR-01.58
  it("tolerates CRLF line endings", () => {
    const screens = parseDesignManifest(MANIFEST.replace(/\n/g, "\r\n"));
    expect(screens).toHaveLength(3);
  });
});
