/*
 * launchPayload.ts — Single source of truth for "what to render and what
 * to copy" for a triage item's launchPayload (iterate-2026-05-20-triage-
 * launch-surface-webui).
 *
 * Two consumers — `<LaunchPayloadBlock>` (renders) and the `Fix now`
 * button in `<TriageDetailModal>` (copies). Both call `prepareLaunchPayload`
 * so the rendered text and the clipboard payload are byte-equal, and so
 * the button-visibility decision uses the same renderability rule as
 * the block.
 *
 * `stripControlChars` is a verbatim port of the canonical Python
 * `aggregate_triage._strip_control_chars`. Parity is verified against
 * `server/src/test/fixtures/launch-payload-strip.json`, which is
 * Python-generated by `server/scripts/regen-launch-payload-fixtures.py`.
 * Re-run that script when shipwright changes the canonical allow-list.
 */

import type { TriageItem } from "./triageApi";

/**
 * Allow-list (verbatim from Python):
 *   - `\n`, `\t` — preserved
 *   - 0x20..0x7E (printable ASCII without DEL)
 *   - >= 0x80 (multibyte: Umlaut, emoji, CJK, …)
 *
 * Everything else (including CR `\r`, DEL `\x7f`, ESC `\x1b`, BEL `\x07`,
 * and the rest of the C0 range) is stripped.
 */
export function stripControlChars(text: string): string {
  let out = "";
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    const code = ch.charCodeAt(0);
    if (ch === "\n" || ch === "\t") {
      out += ch;
    } else if (code >= 0x20 && code < 0x7f) {
      out += ch;
    } else if (code >= 0x80) {
      out += ch;
    }
  }
  return out;
}

export type LaunchPayloadDecision =
  | { kind: "render"; cleaned: string }
  | { kind: "github-placeholder" }
  | { kind: "none" };

/**
 * Source-of-truth decision: given a triage item, what should the UI
 * do with its launchPayload?
 *
 * Order matters (matches `aggregate_triage._render_launch_payload`):
 *   1. Read the raw `launchPayload` field.
 *   2. Strip control chars to produce `cleaned`.
 *   3. If `cleaned.trim()` is non-empty → `render` (regardless of
 *      source). The cleaned string is what both the renderer AND the
 *      Fix-now copy use.
 *   4. Else if `source === "github"` → `github-placeholder` (the
 *      producer is supposed to mint one for every github action-unit;
 *      a missing/empty/cleaned-empty payload from a github item is a
 *      producer bug and must surface loudly).
 *   5. Else → `none` (legacy producer; render nothing).
 */
export function prepareLaunchPayload(item: TriageItem): LaunchPayloadDecision {
  const raw = item.launchPayload;
  if (typeof raw === "string") {
    const cleaned = stripControlChars(raw);
    if (cleaned.trim() !== "") {
      return { kind: "render", cleaned };
    }
  }
  if (item.source === "github") {
    return { kind: "github-placeholder" };
  }
  return { kind: "none" };
}

/**
 * Verbatim copy of the github-source loud-failure placeholder
 * (`aggregate_triage._render_launch_payload`). Exported so the modal,
 * its tests, and any future surface that wants the same text share the
 * literal string.
 */
export const GITHUB_PLACEHOLDER_TEXT =
  "[no launch payload — producer bug; please report]";
