/*
 * launchPayload.test.ts — unit tests for `stripControlChars` (Python
 * parity, fixture-driven) + `prepareLaunchPayload` (decision rule).
 *
 * iterate-2026-05-20-triage-launch-surface-webui external-review
 * findings folded in:
 *   MED #3 + #4 + #11 — single source of truth for renderability;
 *     github placeholder fires on CLEANED-empty, not raw-empty.
 *   MED #6 — parity table is Python-generated, not hand-curated.
 */

import { describe, it, expect } from "vitest";

import {
  GITHUB_PLACEHOLDER_TEXT,
  prepareLaunchPayload,
  stripControlChars,
} from "./launchPayload";
import type { TriageItem } from "./triageApi";
// Vite handles `.json` imports natively. The fixture is Python-
// generated by `server/scripts/regen-launch-payload-fixtures.py` — see
// the comment header in `client/src/test/fixtures/launch-payload-strip.json`.
import stripFixture from "../test/fixtures/launch-payload-strip.json";

interface StripFixtureRow {
  description: string;
  input: string;
  expected: string;
}
interface StripFixture {
  cases: StripFixtureRow[];
}

function makeItem(partial: Partial<TriageItem> = {}): TriageItem {
  return {
    id: "trg-test1234",
    ts: "2026-05-20T08:00:00Z",
    originalTs: "2026-05-20T08:00:00Z",
    source: "phaseQuality",
    severity: "medium",
    kind: "bug",
    title: "Test",
    detail: "Test detail",
    evidencePath: null,
    runId: null,
    commit: null,
    dedupKey: null,
    status: "triage",
    suggestedPriority: "P2",
    suggestedDomain: "engineering",
    statusBy: null,
    statusReason: null,
    promotedTaskId: null,
    ...partial,
  };
}

describe("stripControlChars — Python parity", () => {
  const fixture = stripFixture as StripFixture;

  for (const c of fixture.cases) {
    // @covers FR-01.30
    it(`case "${c.description}" matches the canonical Python output`, () => {
      expect(stripControlChars(c.input)).toBe(c.expected);
    });
  }
});

describe("prepareLaunchPayload — decision rule", () => {
  // @covers FR-01.30
  it("returns kind=render with cleaned payload for a non-empty string", () => {
    const item = makeItem({
      source: "phaseQuality",
      launchPayload: "/iterate foo\n\nhttps://example.test",
    });
    const result = prepareLaunchPayload(item);
    expect(result.kind).toBe("render");
    if (result.kind === "render") {
      expect(result.cleaned).toBe("/iterate foo\n\nhttps://example.test");
    }
  });

  // @covers FR-01.30
  it("strips control chars from the payload before deciding renderability", () => {
    const item = makeItem({
      source: "phaseQuality",
      launchPayload: "before\x1b[31mred\x1b[0mafter",
    });
    const result = prepareLaunchPayload(item);
    expect(result.kind).toBe("render");
    if (result.kind === "render") {
      // ESC stripped; literal `[31m`, `red`, `[0m`, `after` retained.
      expect(result.cleaned).toBe("before[31mred[0mafter");
      // Round-trip invariant: cleaned has no ESC byte.
      expect(result.cleaned.includes("\x1b")).toBe(false);
    }
  });

  // @covers FR-01.30
  it("returns kind=github-placeholder when launchPayload is null and source is github", () => {
    const item = makeItem({ source: "github", launchPayload: null });
    expect(prepareLaunchPayload(item).kind).toBe("github-placeholder");
  });

  // @covers FR-01.30
  it("returns kind=github-placeholder when launchPayload key is missing and source is github", () => {
    const item = makeItem({ source: "github" });
    // launchPayload not set on partial → undefined on item
    expect(prepareLaunchPayload(item).kind).toBe("github-placeholder");
  });

  // @covers FR-01.30
  it("returns kind=github-placeholder when payload contains only control chars (MED #4)", () => {
    const item = makeItem({ source: "github", launchPayload: "\x07\x1b\x7f" });
    // After strip, payload is empty → not renderable → falls to placeholder
    // for source=github. Critical: a raw payload that LOOKS non-empty but
    // collapses to "" must still surface the loud failure.
    expect(prepareLaunchPayload(item).kind).toBe("github-placeholder");
  });

  // @covers FR-01.30
  it("returns kind=github-placeholder when payload is whitespace-only and source is github", () => {
    const item = makeItem({ source: "github", launchPayload: "   \n\t   " });
    expect(prepareLaunchPayload(item).kind).toBe("github-placeholder");
  });

  // @covers FR-01.30
  it("returns kind=none for legacy non-github items with no payload", () => {
    const item = makeItem({ source: "phaseQuality", launchPayload: null });
    expect(prepareLaunchPayload(item).kind).toBe("none");
  });

  // @covers FR-01.30
  it("returns kind=none when payload key is missing and source is non-github", () => {
    const item = makeItem({ source: "compliance" });
    expect(prepareLaunchPayload(item).kind).toBe("none");
  });

  // @covers FR-01.30
  it("returns kind=none when non-github payload is whitespace-only", () => {
    // Whitespace IS technically renderable text on the wire; treating it
    // as none avoids a blank fence for a legacy producer that emitted
    // empty-looking content. Symmetric to the github branch above —
    // both surfaces consider whitespace-only as "not really a payload".
    const item = makeItem({ source: "phaseQuality", launchPayload: "   \n\t   " });
    expect(prepareLaunchPayload(item).kind).toBe("none");
  });

  // @covers FR-01.30
  it("exposes the github placeholder text as a constant (verbatim from aggregator)", () => {
    expect(GITHUB_PLACEHOLDER_TEXT).toBe(
      "[no launch payload — producer bug; please report]",
    );
  });
});
