/*
 * triage-enrich.test.ts — GET-route enrichment layer coverage for
 * iterate-2026-06-10-triage-pending-delivery-badge.
 *
 * enrichPendingDelivery: TRACKED-PREFERRED residence flag mirroring the
 * monorepo `triage_cli.py list --json` contract (shipwright PR #177,
 * trg-e2a0ebb3). The CLI PARITY GATE below compares the TS open-items
 * projection against `triage-union-cli-list.json`, generated by running
 * the REAL CLI — regen via `uv run server/scripts/regen-triage-fixtures.py`.
 *
 * enrichWithCampaignRefs: moved verbatim from routes/triage.ts (anti-ratchet
 * extraction); the FR-01.33 behavior tests live here now, route-level
 * coverage stays in routes/triage.test.ts.
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  mkdtempSync,
  rmSync,
  writeFileSync,
  readFileSync,
  utimesSync,
} from "node:fs";
import path from "node:path";
import { tmpdir } from "node:os";

import {
  enrichPendingDelivery,
  enrichWithCampaignRefs,
  _clearEnrichCache_TEST_ONLY,
} from "./triage-enrich.js";
import { readAllItems, filterTriage, _clearCache_TEST_ONLY } from "./triage-store.js";
import { outboxPathFor } from "./triage-paths.js";
import type { TriageItem } from "../types/triage.js";

const FIXTURE_UNION_TRACKED = path.resolve(
  __dirname,
  "../test/fixtures/triage-union.tracked.jsonl",
);
const FIXTURE_UNION_OUTBOX = path.resolve(
  __dirname,
  "../test/fixtures/triage-union.outbox.jsonl",
);
const FIXTURE_UNION_CLI_LIST = path.resolve(
  __dirname,
  "../test/fixtures/triage-union-cli-list.json",
);

const HEADER = `{"v":1,"schema":"triage","created":"2026-06-01T00:00:00Z"}`;

function appendLine(id: string, ts: string, extra: Record<string, unknown> = {}): string {
  return JSON.stringify({
    event: "append",
    id,
    ts,
    originalTs: ts,
    source: "phaseQuality",
    severity: "high",
    kind: "bug",
    title: `title ${id}`,
    detail: `detail ${id}`,
    evidencePath: null,
    runId: null,
    commit: null,
    dedupKey: `dedup:${id}`,
    status: "triage",
    suggestedPriority: "P1",
    suggestedDomain: "engineering",
    ...extra,
  });
}

function statusLine(id: string, ts: string, newStatus: string): string {
  return JSON.stringify({
    event: "status",
    id,
    ts,
    newStatus,
    by: "webui",
    reason: null,
    promotedTaskId: null,
  });
}

describe("triage-enrich: enrichPendingDelivery", () => {
  let workDir: string;
  let trackedPath: string;
  let outboxPath: string;

  beforeEach(() => {
    _clearCache_TEST_ONLY();
    _clearEnrichCache_TEST_ONLY();
    workDir = mkdtempSync(path.join(tmpdir(), "triage-enrich-"));
    trackedPath = path.join(workDir, "triage.jsonl");
    outboxPath = outboxPathFor(trackedPath);
  });

  afterEach(() => {
    rmSync(workDir, { recursive: true, force: true });
  });

  it("classifies all three residence classes with a CONCRETE boolean on every item", () => {
    writeFileSync(
      trackedPath,
      `${HEADER}\n${appendLine("trg-tracked", "2026-06-01T08:00:00Z")}\n${appendLine(
        "trg-both",
        "2026-06-01T08:01:00Z",
      )}\n`,
    );
    writeFileSync(
      outboxPath,
      appendLine("trg-both", "2026-06-01T08:01:00Z") +
        "\n" +
        appendLine("trg-outonly", "2026-06-01T08:02:00Z") +
        "\n",
    );
    const items = readAllItems(trackedPath);
    enrichPendingDelivery(items, trackedPath);
    const byId = new Map(items.map((i) => [i.id, i]));
    // The residence key is the triage item id (`trg-…`) of `append` events —
    // identical to Python `_append_ids_at` (external review OAI2/Gem4).
    expect(byId.get("trg-tracked")?.pendingDelivery).toBe(false);
    // TRACKED-PREFERRED: present in BOTH files (post-sweep, pre-GC) → NOT pending.
    expect(byId.get("trg-both")?.pendingDelivery).toBe(false);
    expect(byId.get("trg-outonly")?.pendingDelivery).toBe(true);
    // AC1 / external review OAI1: a concrete boolean on EVERY item, never undefined.
    for (const it of items) {
      expect(typeof it.pendingDelivery).toBe("boolean");
    }
  });

  it("annotates CLOSED items too (residence is status-independent)", () => {
    writeFileSync(outboxPath, [
      appendLine("trg-dismissed-out", "2026-06-01T08:00:00Z"),
      statusLine("trg-dismissed-out", "2026-06-01T09:00:00Z", "dismissed"),
    ].join("\n") + "\n");
    const items = readAllItems(trackedPath);
    enrichPendingDelivery(items, trackedPath);
    expect(items[0].status).toBe("dismissed");
    expect(items[0].pendingDelivery).toBe(true);
  });

  it("treats a MISSING tracked file as an empty residence set (outbox-only project)", () => {
    writeFileSync(outboxPath, appendLine("trg-fresh", "2026-06-01T08:00:00Z") + "\n");
    const items = readAllItems(trackedPath);
    enrichPendingDelivery(items, trackedPath);
    expect(items[0].pendingDelivery).toBe(true);
  });

  it("treats a MISSING outbox file as an empty residence set (all items false, no throw)", () => {
    writeFileSync(trackedPath, `${HEADER}\n${appendLine("trg-a", "2026-06-01T08:00:00Z")}\n`);
    const items = readAllItems(trackedPath);
    enrichPendingDelivery(items, trackedPath);
    expect(items[0].pendingDelivery).toBe(false);
  });

  it("matches the REAL `triage_cli.py list --json` contract on the union fixtures (CLI PARITY GATE)", () => {
    // The exact CLI projection: open items only, plus pendingDelivery —
    // campaign enrichment deliberately NOT applied (external review OAI5).
    writeFileSync(trackedPath, readFileSync(FIXTURE_UNION_TRACKED, "utf-8"));
    writeFileSync(outboxPath, readFileSync(FIXTURE_UNION_OUTBOX, "utf-8"));
    const open = filterTriage(readAllItems(trackedPath)).map((it) => ({ ...it }));
    enrichPendingDelivery(open, trackedPath);
    const expected = JSON.parse(readFileSync(FIXTURE_UNION_CLI_LIST, "utf-8")) as {
      items: unknown[];
    };
    expect(open).toEqual(expected.items);
  });

  it("memoizes residence sets by both mtimes and invalidates when the TRACKED file changes", () => {
    writeFileSync(trackedPath, `${HEADER}\n${appendLine("trg-t1", "2026-06-01T08:00:00Z")}\n`);
    writeFileSync(outboxPath, appendLine("trg-o1", "2026-06-01T08:01:00Z") + "\n");
    const items = readAllItems(trackedPath);
    enrichPendingDelivery(items, trackedPath);
    expect(items.find((i) => i.id === "trg-o1")?.pendingDelivery).toBe(true);
    // Sweep simulation: the same id lands in tracked; outbox unchanged in
    // content but tracked mtime moves → memo must invalidate → both-files
    // residence flips the flag to false (TRACKED-PREFERRED).
    writeFileSync(
      trackedPath,
      `${HEADER}\n${appendLine("trg-t1", "2026-06-01T08:00:00Z")}\n${appendLine(
        "trg-o1",
        "2026-06-01T08:01:00Z",
      )}\n`,
    );
    const future = new Date(Date.now() + 10_000);
    utimesSync(trackedPath, future, future);
    const items2 = readAllItems(trackedPath).map((it) => ({ ...it }));
    enrichPendingDelivery(items2, trackedPath);
    expect(items2.find((i) => i.id === "trg-o1")?.pendingDelivery).toBe(false);
  });

  it("invalidates the memo when the OUTBOX changes (new background append within TTL)", () => {
    writeFileSync(trackedPath, `${HEADER}\n${appendLine("trg-t2", "2026-06-01T08:00:00Z")}\n`);
    const items = readAllItems(trackedPath);
    enrichPendingDelivery(items, trackedPath);
    expect(items[0].pendingDelivery).toBe(false);
    // A background producer appends to the outbox; outbox mtime moves →
    // memo (keyed on BOTH mtimes) must miss and pick up the new resident.
    writeFileSync(outboxPath, appendLine("trg-o2", "2026-06-01T08:05:00Z") + "\n");
    const future = new Date(Date.now() + 10_000);
    utimesSync(outboxPath, future, future);
    const items2 = readAllItems(trackedPath).map((it) => ({ ...it }));
    enrichPendingDelivery(items2, trackedPath);
    expect(items2.find((i) => i.id === "trg-o2")?.pendingDelivery).toBe(true);
    expect(items2.find((i) => i.id === "trg-t2")?.pendingDelivery).toBe(false);
  });
});

describe("triage-enrich: enrichWithCampaignRefs (moved verbatim from routes/triage.ts)", () => {
  const baseItem = (id: string): TriageItem => ({
    id,
    ts: "2026-06-01T08:00:00Z",
    originalTs: "2026-06-01T08:00:00Z",
    source: "phaseQuality",
    severity: "high",
    kind: "bug",
    title: `title ${id}`,
    detail: `detail ${id}`,
    evidencePath: null,
    runId: null,
    commit: null,
    dedupKey: `dedup:${id}`,
    status: "triage",
    suggestedPriority: "P1",
    suggestedDomain: "engineering",
    statusBy: null,
    statusReason: null,
    promotedTaskId: null,
  });

  it("annotates the matching item and prefers draft over active over complete", () => {
    const items = [baseItem("trg-c1")];
    enrichWithCampaignRefs(items, "proj", () => [
      { expandsTriage: "trg-c1", slug: "older-active", status: "active" },
      { expandsTriage: "trg-c1", slug: "newer-draft", status: "draft" },
    ]);
    expect(items[0].campaignSlug).toBe("newer-draft");
    expect(items[0].campaignStatus).toBe("draft");
  });

  it("is a no-op without the dep and swallows a throwing dep (best-effort)", () => {
    const items = [baseItem("trg-c2")];
    enrichWithCampaignRefs(items, "proj", undefined);
    expect(items[0].campaignSlug).toBeUndefined();
    enrichWithCampaignRefs(items, "proj", () => {
      throw new Error("campaign store down");
    });
    expect(items[0].campaignSlug).toBeUndefined();
  });
});
