/*
 * triage-contract.test.ts — CLI-parity envelope coverage for
 * iterate-2026-08-05-triage-deferred-envelope (monorepo P2.03,
 * CONTRACT_VERSION 2).
 *
 * The CLI PARITY GATE compares `buildTriageListing`'s output against
 * `triage-union-cli-list.json`, generated by running the REAL
 * `triage_cli.py list --json` — regen via
 * `uv run server/scripts/regen-triage-fixtures.py`. Moved from
 * triage-enrich.test.ts, whose `filterTriage(readAllItems()) +
 * enrichPendingDelivery` combo described the OLD bare-list contract.
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, writeFileSync, readFileSync } from "node:fs";
import path from "node:path";
import { tmpdir } from "node:os";

import { buildTriageListing, CONTRACT_VERSION } from "./triage-contract.js";
import { readAllItems, _clearCache_TEST_ONLY } from "./triage-store.js";
import { outboxPathFor } from "./triage-paths.js";

const FIXTURE_UNION_TRACKED = path.resolve(
  __dirname,
  "../test/fixtures/triage-union.tracked.jsonl",
);
const FIXTURE_UNION_OUTBOX = path.resolve(
  __dirname,
  "../test/fixtures/triage-union.outbox.jsonl",
);
const FIXTURE_UNION_CLI_LIST = path.resolve(
  __dirname,
  "../test/fixtures/triage-union-cli-list.json",
);

describe("triage-contract: buildTriageListing — CLI PARITY GATE", () => {
  let workDir: string;
  let trackedPath: string;
  let outboxPath: string;

  beforeEach(() => {
    _clearCache_TEST_ONLY();
    workDir = mkdtempSync(path.join(tmpdir(), "triage-contract-"));
    trackedPath = path.join(workDir, "triage.jsonl");
    outboxPath = outboxPathFor(trackedPath);
  });

  afterEach(() => {
    rmSync(workDir, { recursive: true, force: true });
  });

  it("matches the REAL `triage_cli.py list --json` envelope byte-for-byte (deep-equal)", () => {
    writeFileSync(trackedPath, readFileSync(FIXTURE_UNION_TRACKED, "utf-8"));
    writeFileSync(outboxPath, readFileSync(FIXTURE_UNION_OUTBOX, "utf-8"));
    const listing = buildTriageListing(readAllItems(trackedPath), trackedPath);
    const expected = JSON.parse(readFileSync(FIXTURE_UNION_CLI_LIST, "utf-8")) as {
      contractVersion: number;
      open: unknown[];
      deferred: unknown[];
    };
    expect(listing).toEqual({
      contractVersion: expected.contractVersion,
      open: expected.open,
      deferred: expected.deferred,
    });
  });

  it("contractVersion is 2, matching the monorepo's CONTRACT_VERSION", () => {
    expect(CONTRACT_VERSION).toBe(2);
    writeFileSync(trackedPath, readFileSync(FIXTURE_UNION_TRACKED, "utf-8"));
    writeFileSync(outboxPath, readFileSync(FIXTURE_UNION_OUTBOX, "utf-8"));
    const listing = buildTriageListing(readAllItems(trackedPath), trackedPath);
    expect(listing.contractVersion).toBe(2);
  });
});

describe("triage-contract: buildTriageListing — unit behavior", () => {
  let workDir: string;
  let trackedPath: string;

  beforeEach(() => {
    _clearCache_TEST_ONLY();
    workDir = mkdtempSync(path.join(tmpdir(), "triage-contract-unit-"));
    trackedPath = path.join(workDir, "triage.jsonl");
  });

  afterEach(() => {
    rmSync(workDir, { recursive: true, force: true });
  });

  it("splits open (status:triage) from deferred (status:snoozed); other statuses appear in neither", () => {
    writeFileSync(
      trackedPath,
      [
        `{"v":1,"schema":"triage","created":"2026-06-01T00:00:00Z"}`,
        appendLine("trg-open"),
        appendLine("trg-parked"),
        statusLine("trg-parked", "snoozed", { revisitAt: "2099-01-01" }),
        appendLine("trg-dismissed"),
        statusLine("trg-dismissed", "dismissed"),
      ].join("\n") + "\n",
    );
    const listing = buildTriageListing(readAllItems(trackedPath), trackedPath);
    expect(listing.open.map((i) => i.id)).toEqual(["trg-open"]);
    expect(listing.deferred.map((i) => i.id)).toEqual(["trg-parked"]);
  });

  it("every open and deferred item carries a concrete pendingDelivery boolean", () => {
    writeFileSync(
      trackedPath,
      [
        `{"v":1,"schema":"triage","created":"2026-06-01T00:00:00Z"}`,
        appendLine("trg-open"),
        appendLine("trg-parked"),
        statusLine("trg-parked", "snoozed", { revisitAt: "2099-01-01" }),
      ].join("\n") + "\n",
    );
    const listing = buildTriageListing(readAllItems(trackedPath), trackedPath);
    for (const it of [...listing.open, ...listing.deferred]) {
      expect(typeof it.pendingDelivery).toBe("boolean");
    }
  });

  it("deferred is never capped — every snoozed item appears, however many", () => {
    const lines = [`{"v":1,"schema":"triage","created":"2026-06-01T00:00:00Z"}`];
    for (let i = 0; i < 25; i++) {
      const id = `trg-park-${String(i).padStart(3, "0")}`;
      lines.push(appendLine(id), statusLine(id, "snoozed", { revisitAt: "2099-01-01" }));
    }
    writeFileSync(trackedPath, lines.join("\n") + "\n");
    const listing = buildTriageListing(readAllItems(trackedPath), trackedPath);
    expect(listing.deferred).toHaveLength(25);
  });
});

function appendLine(id: string): string {
  return JSON.stringify({
    event: "append",
    id,
    ts: "2026-06-01T08:00:00Z",
    originalTs: "2026-06-01T08:00:00Z",
    source: "phaseQuality",
    severity: "high",
    kind: "bug",
    title: `title ${id}`,
    detail: `detail ${id}`,
    evidencePath: null,
    runId: null,
    commit: null,
    dedupKey: `dedup:${id}`,
    status: "triage",
    suggestedPriority: "P1",
    suggestedDomain: "engineering",
  });
}

function statusLine(
  id: string,
  newStatus: string,
  extra: Record<string, unknown> = {},
): string {
  return JSON.stringify({
    event: "status",
    id,
    ts: "2026-06-01T09:00:00Z",
    newStatus,
    by: "webui",
    reason: null,
    promotedTaskId: null,
    ...extra,
  });
}
