// Auto-generated by /shipwright-adopt on 2026-04-30.
// Purpose: regression guard — fails if basic navigation breaks.
// Refine these tests with real acceptance criteria as features evolve via /shipwright-iterate.

import { test, expect } from '@playwright/test';

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

test('FR-01.01 — / (Shipwright Command Center)', async ({ page }) => {
  await page.goto('/');
  await expect(page).toHaveURL(new RegExp(escapeRegex('/')));
  await expect(page.getByRole('button', { name: /All\ projects\ 9\ tasks/i }).or(page.getByText('All projects 9 tasks'))).toBeVisible();
  await expect(page.getByRole('button', { name: /Board/i }).or(page.getByText('Board'))).toBeVisible();
  await expect(page.getByRole('button', { name: /List/i }).or(page.getByText('List'))).toBeVisible();
});

test('FR-01.02 — /projects (Shipwright Command Center)', async ({ page }) => {
  await page.goto('/projects');
  await expect(page).toHaveURL(new RegExp(escapeRegex('/projects')));
  await expect(page.locator('h1').first()).toContainText('Projects');
  await expect(page.getByRole('button', { name: /Create\ Project/i }).or(page.getByText('Create Project'))).toBeVisible();
});

test('FR-01.03 — /inbox (Shipwright Command Center)', async ({ page }) => {
  await page.goto('/inbox');
  await expect(page).toHaveURL(new RegExp(escapeRegex('/inbox')));
  await expect(page.locator('h1').first()).toContainText('Inbox');
});

test('FR-01.04 — /settings (Shipwright Command Center)', async ({ page }) => {
  await page.goto('/settings');
  await expect(page).toHaveURL(new RegExp(escapeRegex('/settings')));
  await expect(page.locator('h1').first()).toContainText('Settings');
});

test('FR-01.05 — /diagnostics (Shipwright Command Center)', async ({ page }) => {
  await page.goto('/diagnostics');
  await expect(page).toHaveURL(new RegExp(escapeRegex('/diagnostics')));
  await expect(page.locator('h1').first()).toContainText('Diagnostics');
});

test('FR-01.06 — /tmp/dry-run (Shipwright Command Center)', async ({ page }) => {
  await page.goto('/tmp/dry-run');
  await expect(page).toHaveURL(new RegExp(escapeRegex('/tmp/dry-run')));
});

