"""Tests for `is_generated_path` — the membership POLICY.

What counts as a producer-generated artifact, and — the half that matters on an
untrusted-input gate — what does NOT. Three things are deliberately outside the
set and pinned as such: dependency lockfiles, the authored files under
`.shipwright/agent_docs/`, and (this repo's own adaptation)
`server/src/test/fixtures/triage.jsonl`, an authored test fixture that a
basename rule would have swallowed (that family lives in
test_pr_review_generated_collisions.py).

The MECHANISM that consumes this policy — where a file section begins and ends —
is pinned in test_pr_review_filter.py. The test modules mirror the source split
(`pr_review_generated` vs `pr_review_diff_filter`) and each stays under the
source-size guideline.

Vendored from the canonical monorepo (plugins/shipwright-security/tests/
test_pr_review_filter.py); fixtures re-pointed to the WebUI tree.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

CI_DIR = Path(__file__).resolve().parent.parent  # scripts/ci
REPO_ROOT = CI_DIR.parent.parent
sys.path.insert(0, str(CI_DIR))

import pr_review_generated as G  # noqa: E402
import pr_review_lib as L  # noqa: E402


def _section(path: str, body: str = "@@ -1 +1 @@\n-old\n+new\n") -> str:
    return f"diff --git a/{path} b/{path}\nindex 111..222 100644\n--- a/{path}\n+++ b/{path}\n{body}"


class TestIsGeneratedPath:
    def test_compliance_prefix(self):
        assert L.is_generated_path(".shipwright/compliance/dashboard.md")

    def test_the_three_regenerated_agent_docs(self):
        for name in ("build_dashboard.md", "session_handoff.md", "triage_inbox.md"):
            assert L.is_generated_path(f".shipwright/agent_docs/{name}"), name
        assert L.is_generated_path(".shipwright/agent_docs/iterates/run-x.json")
        assert L.is_generated_path(".shipwright/agent_docs/runtime/whatever.json")

    def test_authored_agent_docs_are_NOT_generated(self):
        """The directory is this repo's agent-instruction surface.

        A blanket `.shipwright/agent_docs/` prefix hid `architecture.md` (curated
        prose the churn resolver specifically refuses to auto-merge), the
        component inventory, and the hand-written conventions / decision log —
        from the one reviewer whose own system prompt orders it to BLOCK on an
        injected instruction in agent markdown. Same error as the lockfile one,
        one prefix earlier.
        """
        for name in ("architecture.md", "component_inventory.md", "conventions.md",
                     "decision_log.md", "known_issues.md", "design_tokens.md",
                     "test_status_overrides.md"):
            assert not L.is_generated_path(f".shipwright/agent_docs/{name}"), name

    def test_the_regenerated_agent_doc_set_is_exactly_three_and_they_exist(self):
        """Both drift directions, as far as this repo can pin them.

        The canonical copy reads the monorepo's own churn allowlist
        (`shared/scripts/lib/churn_merge.AGENT_DOC_MDS`) as the SSoT; there is no
        Python `shared/` tree on this runner, so the three names are literal here
        — which makes them exactly the kind of registry that rots silently. The
        reverse direction is therefore pinned against the repo itself: each name
        must be a file that actually exists, so a rename upstream turns this red
        rather than leaving a dead entry that quietly filters nothing.
        """
        assert len(G._GENERATED_AGENT_DOCS) == 3, sorted(G._GENERATED_AGENT_DOCS)
        for rel in G._GENERATED_AGENT_DOCS:
            assert (REPO_ROOT / rel).exists(), f"{rel} is in the set but not in the repo"

    def test_changelog_drops_prefix(self):
        assert L.is_generated_path("CHANGELOG-unreleased.d/Added/foo_001.md")

    def test_a_lockfile_is_NOT_generated(self):
        """A dependency lockfile is reviewable, and on an untrusted PR it is the
        most reviewable thing in the diff — it is where a substituted or
        typosquatted package arrives, regenerated by whoever opened the PR.
        Filtering it hid every dependency change that shared a PR with one
        ordinary file. This repo ships two of them (server/ and client/ are
        independent npm workspaces), so the shape is routine here."""
        for lock in ("package-lock.json", "server/package-lock.json",
                     "client/package-lock.json", "uv.lock", "poetry.lock",
                     "Cargo.lock", "yarn.lock", "pnpm-lock.yaml"):
            assert not L.is_generated_path(lock), lock

    def test_state_logs(self):
        assert L.is_generated_path("shipwright_test_results.json")
        assert L.is_generated_path("shipwright_events.jsonl")
        assert L.is_generated_path(".shipwright/triage.jsonl")
        assert L.is_generated_path(".shipwright/triage.outbox.jsonl")


class TestReviewEvidenceExcluded:
    """A reviewer must not be fed the transcripts of prior reviews.

    `reviews.json` (record_review_pass) and the `*-external-*review*.json`
    replies (external_review) are tool-written records OF a review. Reviewing
    them is circular, and they are bulky.
    """

    RUN = ".shipwright/planning/iterate/iterate-2026-07-28-a-run"

    def test_review_record_is_excluded(self):
        assert L.is_generated_path(f"{self.RUN}/reviews.json")

    def test_raw_external_review_replies_are_excluded(self):
        for name in (
            "iterate-2026-07-28-a-run-external-review.json",
            "iterate-2026-07-28-a-run-external-code-review.json",
            "iterate-2026-07-28-a-run-external-code-review-head.json",
            "iterate-2026-07-28-a-run-external-code-review-final.json",
        ):
            assert L.is_generated_path(
                f".shipwright/planning/iterate/{name}"), name

    def test_the_iterate_spec_and_miniplan_stay_reviewable(self):
        """The narrow half of the rule, and the point of it.

        These are AUTHORED, they state the acceptance criteria, and they are
        the intent a reviewer should read the diff against. Excluding them
        would trade a size win for review quality.
        """
        assert not L.is_generated_path(
            ".shipwright/planning/iterate/2026-07-28-a-run.md")
        assert not L.is_generated_path(
            ".shipwright/planning/iterate/2026-07-28-a-run-miniplan.md")

    def test_a_json_elsewhere_under_planning_is_not_excluded(self):
        # The rule is scoped to the iterate run directory, not all planning.
        assert not L.is_generated_path(
            ".shipwright/planning/01-adopted/reviews.json")
        assert not L.is_generated_path("server/src/reviews.json")

    def test_an_unrelated_json_in_the_run_dir_is_not_excluded(self):
        assert not L.is_generated_path(f"{self.RUN}/result.json")

    def test_the_sections_are_dropped_from_a_real_diff(self):
        diff = (
            _section("server/src/core/launcher.ts")
            + _section(f"{self.RUN}/reviews.json")
            + _section(".shipwright/planning/iterate/run-external-review.json")
            + _section(".shipwright/planning/iterate/run.md")
        )
        filtered, excluded = L.filter_generated_paths(diff)

        assert "launcher.ts" in filtered
        assert "run.md" in filtered            # authored intent survives
        assert "reviews.json" not in filtered
        assert "external-review.json" not in filtered
        assert len(excluded) == 2

    def test_real_source_not_generated(self):
        assert not L.is_generated_path("server/src/core/path-guard.ts")
        assert not L.is_generated_path("scripts/ci/pr_review_lib.py")
        assert not L.is_generated_path(".github/workflows/ci.yml")
        # a hand-authored planning doc / ADR is source, not generated
        assert not L.is_generated_path(".shipwright/planning/adr/135-mission.md")
