"""RATCHET over the Semgrep scan-SCOPE channel — `.semgrepignore`.

One of two channels this repo uses that `accepted_risks_cli.py check` cannot
see. CLAUDE.md DO-NOT #25 says the register gate covers THREE channels (a
`.trivyignore.yaml` id and the two `SHIPWRIGHT_SEMGREP_*` keys in security.yml)
and names what stays open; this is the largest of those, because one line here
silences an entire subtree, permanently, with no expiry.

WHY A RATCHET AND NOT REGISTER ENTRIES. Decided after a Codex cross-check
(triage trg-ab54e3d1) and deliberately not reopened. This list is a scan-SCOPE
definition, not a risk acceptance: it excludes artifacts that are not shipped,
exactly as `.github/codeql/codeql-config.yml` already does under its own
recorded decision, and the register's own header forbids using it to silence
REACHABLE findings. Registering these would create perpetual-renewal entries
with no security value.

So the set is pinned exactly, both directions, and every entry carries a
rationale — a bare pinned list buys drift control and not governance (the
cross-check's caveat, accepted). Adding an exclusion now fails CI until the
justification is written, which is the moment it is answerable.

Sibling: `test_semgrep_inline_suppressions.py` (the per-site channel). Shared
discovery: `semgrep_channels.py`. Scanner regression tests:
`test_semgrep_channels_scanner.py`.
"""

from __future__ import annotations

from semgrep_channels import MIN_RATIONALE, excluded, live_patterns

#: `.semgrepignore` pattern -> why the excluded files are NOT shipped.
_SCOPE_PATTERNS: dict[str, str] = {
    "*.test.ts":
        "Vitest unit/integration suites. Not shipped and not reachable at "
        "runtime; scanning them produced audit-rule noise that GitHub "
        "code-scanning inflated to 'high' while the dashboard graded the same "
        "findings 'low' (trg-4c0ab9b0). See iterate-2026-06-30-semgrep-fp-suppression.",
    "*.test.tsx":
        "Vitest component suites. Same reasoning as *.test.ts: test-only code, "
        "never bundled into the client or server artifact.",
    "*.test.mjs":
        "Vitest suites for the plain-ESM modules (bootstrapper helpers). "
        "Same reasoning as *.test.ts.",
    "*.spec.ts":
        "Playwright E2E specs. Driver code that runs against a dev stack and is "
        "never shipped; its child_process and fs use is the harness, not the product.",
    "*.spec.tsx":
        "Playwright/component specs in TSX. Same reasoning as *.spec.ts.",
    "client/e2e/":
        "The Playwright suite's fixtures, helpers and config. Harness-only, not "
        "part of the client bundle. Anchored, so it cannot match elsewhere.",
    "server/scripts/regen-launch-payload-fixtures.py":
        "Dev-time fixture regenerator, invoked by hand via `uv run`. Not imported "
        "by the server and not referenced by any npm script. Named file-by-file "
        "rather than by directory — see the narrowing test below.",
    "server/scripts/regen-triage-fixtures.py":
        "Dev-time fixture regenerator, invoked by hand via `uv run`. Not imported "
        "by the server and not referenced by any npm script.",
    "server/scripts/sdk-poc.ts":
        "One-off SDK proof-of-concept from the Plan-D'' investigation. Not "
        "imported by the server, not referenced by any npm script, and carried in "
        "shipwright_bloat_baseline.json as a known-large POC.",
    ".shipwright/":
        "SDLC planning, compliance and agent-doc artifacts. Markdown, JSON and "
        "JSONL records — documentation, not executable code.",
    "dist/":
        "Build OUTPUT, at any depth (client/dist, server/dist). Scanning it "
        "double-reports whatever the sources already report.",
    "build/":
        "Build output at any depth. Same reasoning as dist/: generated bytes, "
        "reported once already via the sources they were generated from.",
    "node_modules/":
        "Vendored third-party dependencies at any depth. Dependency risk is "
        "Trivy's channel (SCA), not Semgrep's SAST channel; scanning them here "
        "would duplicate it with no ownership.",
}


def test_scan_scope_patterns_match_the_pinned_set() -> None:
    """Both directions: disk -> registry and registry -> disk.

    Cannot pass vacuously: an empty or unreadable `.semgrepignore` leaves every
    pinned pattern in the `stale` set below and fails there.
    """
    live = set(live_patterns())
    pinned = set(_SCOPE_PATTERNS)

    unregistered = sorted(live - pinned)
    assert not unregistered, (
        f"these .semgrepignore patterns are live but not pinned: {unregistered}.\n"
        "Each one removes a subtree from the security scan permanently, with no "
        "expiry and nothing else able to see it. Add an entry to _SCOPE_PATTERNS "
        "explaining why the excluded files are NOT shipped. If the goal is to "
        "silence a REACHABLE finding, this is the wrong channel — that is a risk "
        "acceptance and belongs in shipwright_accepted_risks.yaml."
    )
    stale = sorted(pinned - live)
    assert not stale, (
        f"these patterns are pinned here but no longer in .semgrepignore: {stale}.\n"
        "Remove the entry in the same change, or this registry starts describing "
        "a scan scope that does not exist."
    )


def test_every_scan_scope_pattern_carries_a_rationale() -> None:
    thin = sorted(
        pattern
        for pattern, rationale in _SCOPE_PATTERNS.items()
        if len(rationale.strip()) < MIN_RATIONALE
    )
    assert not thin, (
        f"these scope patterns have no usable rationale: {thin}.\n"
        "A pinned list alone buys drift control, not governance. Say why the "
        "excluded files are not shipped, or point at the decision that says so."
    )


def test_the_build_shaping_script_is_in_scan_scope() -> None:
    """`server/scripts/` was excluded wholesale; one file in it ships.

    `server/package.json` runs `"build": "tsc && node scripts/copy-assets.mjs"`,
    and that script copies `src/config` -> `dist/config`. Without it
    `node dist/index.js` ENOENTs on `dist/config/default-actions.json` — which is
    exactly why `server/src/test/build-assets.test.ts` exists. It shapes the
    SHIPPED artifact, so the blanket exclusion was excluding production code, not
    a dev script. Found by the Codex cross-check on trg-ab54e3d1.
    """
    patterns = live_patterns()
    assert "server/scripts/" not in patterns, (
        "`server/scripts/` is back as a blanket exclusion. That directory is not "
        "purely non-production: copy-assets.mjs is wired into the server build "
        "and decides what lands in dist/. Exclude the non-shipped files by name."
    )
    assert not excluded("server/scripts/copy-assets.mjs", patterns), (
        "server/scripts/copy-assets.mjs is excluded from the security scan, but "
        "`server/package.json` runs it as the second half of `npm run build`. "
        "Production code must stay in scope."
    )
    for rel in (
        "server/scripts/sdk-poc.ts",
        "server/scripts/regen-triage-fixtures.py",
        "server/scripts/regen-launch-payload-fixtures.py",
    ):
        assert excluded(rel, patterns), (
            f"{rel} is no longer excluded from the scan. If that is intentional, "
            "drop its _SCOPE_PATTERNS entry in the same change; if not, restore "
            "the pattern."
        )
