# Shipwright Command Center — Windows Installation
# Creates a startup shortcut so the server starts automatically on Windows login.

param(
    [switch]$Uninstall,
    [int]$Port = 3847
)

$ErrorActionPreference = "Stop"
$WebuiRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
# Resolve to webui dir (script is in webui/scripts/)
$WebuiRoot = Join-Path (Split-Path -Parent $PSScriptRoot) ""
$ServerDir = Join-Path $WebuiRoot "server"
$ClientDir = Join-Path $WebuiRoot "client"
$StartupFolder = [Environment]::GetFolderPath("Startup")
$ShortcutPath = Join-Path $StartupFolder "Shipwright Server.lnk"
$VbsPath = Join-Path $env:USERPROFILE ".shipwright-webui\start-server.vbs"
$VbsDir = Split-Path -Parent $VbsPath

Write-Host "`n  Shipwright Command Center — Windows Setup" -ForegroundColor Cyan
Write-Host "  =========================================`n"

if ($Uninstall) {
    Write-Host "  Removing startup shortcut..." -ForegroundColor Yellow
    if (Test-Path $ShortcutPath) {
        Remove-Item $ShortcutPath -Force
        Write-Host "  Removed: $ShortcutPath" -ForegroundColor Green
    }
    if (Test-Path $VbsPath) {
        Remove-Item $VbsPath -Force
        Write-Host "  Removed: $VbsPath" -ForegroundColor Green
    }
    Write-Host "`n  Uninstalled. Server will no longer start on login.`n" -ForegroundColor Green
    exit 0
}

# 1. Check prerequisites
Write-Host "  [1/4] Checking prerequisites..."
$nodeVersion = & node --version 2>$null
if (-not $nodeVersion) {
    Write-Host "  ERROR: Node.js not found. Install it from https://nodejs.org" -ForegroundColor Red
    exit 1
}
Write-Host "         Node.js $nodeVersion"

# 2. Install dependencies.
#    Native `npm` exit codes are NOT trapped by $ErrorActionPreference="Stop"
#    (that only traps PowerShell cmdlet errors), so each step is gated on
#    $LASTEXITCODE explicitly. Errors are NOT redirected to $null: a new client
#    dependency lands in package-lock.json on `git pull` but is absent from
#    node_modules until this runs — a swallowed install/build failure would
#    silently create a startup shortcut pointing at a server that won't run.
Write-Host "  [2/4] Installing dependencies..."
Push-Location $ServerDir
& npm install
$code = $LASTEXITCODE
Pop-Location
if ($code -ne 0) {
    Write-Host "  ERROR: server npm install failed (exit $code). Aborting." -ForegroundColor Red
    exit 1
}
Push-Location $ClientDir
& npm install
$code = $LASTEXITCODE
Pop-Location
if ($code -ne 0) {
    Write-Host "  ERROR: client npm install failed (exit $code). Aborting." -ForegroundColor Red
    exit 1
}
Write-Host "         Done."

# 3. Build server + client for production (same exit-code gating as step 2).
Write-Host "  [3/4] Building server + client..."
Push-Location $ServerDir
& npm run build
$code = $LASTEXITCODE
Pop-Location
if ($code -ne 0) {
    Write-Host "  ERROR: server build failed (exit $code). Aborting." -ForegroundColor Red
    exit 1
}
Push-Location $ClientDir
& npm run build
$code = $LASTEXITCODE
Pop-Location
if ($code -ne 0) {
    Write-Host "  ERROR: client build failed (exit $code). Aborting." -ForegroundColor Red
    exit 1
}
Write-Host "         Done."

# 4. Create startup script (VBS wrapper runs node hidden, no console window)
Write-Host "  [4/4] Creating Windows startup entry..."

if (-not (Test-Path $VbsDir)) {
    New-Item -ItemType Directory -Path $VbsDir -Force | Out-Null
}

# VBS script that starts the compiled server without a visible console
# window. Runs node against server/dist/index.js (produced in step 3) so
# the launcher path matches the production build artefact, not the tsx
# dev-loop. `--env-file-if-exists=../.env.local` loads the repo-root
# .env.local (network profile etc.) — same as the `npm run dev` script.
# Without it the autostart server would bind differently from the dev
# server (e.g. loopback instead of the Tailscale address) and the UI
# would be unreachable on the address you normally use.
$serverEntryPoint = Join-Path $ServerDir "dist\index.js"
# Backslashes are doubled for embedding (pre-existing behavior — Windows path
# APIs collapse redundant separators, so ASCII-path autostart has always worked).
# Compute the escaped forms ONCE and reuse them below AND in the round-trip check,
# so the check compares against exactly what was written (no recomputation drift).
$escapedServerDir = $ServerDir -replace '\\', '\\'
$escapedEntryPoint = $serverEntryPoint -replace '\\', '\\'
$vbsContent = @"
' Shipwright Command Center — Background Server Launcher
' Auto-generated by install-windows.ps1
Set WshShell = CreateObject("WScript.Shell")
WshShell.CurrentDirectory = "$escapedServerDir"
WshShell.Run "cmd /c set PORT=$Port && node --env-file-if-exists=../.env.local ""$escapedEntryPoint"" > ""%USERPROFILE%\.shipwright-webui\server.log"" 2>&1", 0, False
"@

# Write UTF-16LE (-Encoding Unicode): wscript.exe reads it natively, and unlike
# -Encoding ASCII it does NOT map non-ASCII path characters (umlauts / accents /
# CJK — e.g. C:\Users\Müller\...) to "?", which would silently corrupt the baked-in
# $ServerDir / $serverEntryPoint and break the login autostart.
Set-Content -Path $VbsPath -Value $vbsContent -Encoding Unicode

# Sanity check: re-read the launcher and confirm the embedded server path survived
# the file encoding round-trip (compared against the exact escaped form written
# above). A corrupting encoding (e.g. a future revert to ASCII) would turn a
# non-ASCII install path into "?" characters and silently break autostart while
# still reporting success — fail loudly and remove the bad launcher instead.
# ($serverEntryPoint's non-ASCII chars are a subset of $ServerDir's prefix, so
# verifying $ServerDir survived is sufficient to prove no path char was lost.)
$vbsWritten = Get-Content -Path $VbsPath -Raw -Encoding Unicode
if (-not $vbsWritten.Contains($escapedServerDir)) {
    Remove-Item $VbsPath -Force -ErrorAction SilentlyContinue
    Write-Host "  ERROR: VBS launcher path failed to round-trip after writing." -ForegroundColor Red
    Write-Host "         The install path may contain characters the file encoding cannot represent." -ForegroundColor Red
    Write-Host "         Path: $ServerDir" -ForegroundColor Red
    Write-Host "         Autostart NOT configured. Aborting." -ForegroundColor Red
    exit 1
}

# Create shortcut in Startup folder
$WScriptShell = New-Object -ComObject WScript.Shell
$Shortcut = $WScriptShell.CreateShortcut($ShortcutPath)
$Shortcut.TargetPath = $VbsPath
$Shortcut.WorkingDirectory = $ServerDir
$Shortcut.Description = "Shipwright Command Center Server"
$Shortcut.Save()

Write-Host "         Startup shortcut: $ShortcutPath"
Write-Host "         Server launcher:  $VbsPath"
Write-Host ""
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  The server will start automatically on next Windows login."
Write-Host "  To start it now:  cd server && node dist/index.js"
Write-Host "  To open the UI:   http://localhost:$Port"
Write-Host "  To uninstall:     .\install-windows.ps1 -Uninstall"
Write-Host ""
