# Shipwright Command Center — Windows Installation
# Creates a startup shortcut so the server starts automatically on Windows login.

param(
    [switch]$Uninstall,
    [int]$Port = 3847
)

$ErrorActionPreference = "Stop"
$WebuiRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
# Resolve to webui dir (script is in webui/scripts/)
$WebuiRoot = Join-Path (Split-Path -Parent $PSScriptRoot) ""
$ServerDir = Join-Path $WebuiRoot "server"
$ClientDir = Join-Path $WebuiRoot "client"
$StartupFolder = [Environment]::GetFolderPath("Startup")
$ShortcutPath = Join-Path $StartupFolder "Shipwright Server.lnk"
$VbsPath = Join-Path $env:USERPROFILE ".shipwright-webui\start-server.vbs"
$VbsDir = Split-Path -Parent $VbsPath

Write-Host "`n  Shipwright Command Center — Windows Setup" -ForegroundColor Cyan
Write-Host "  =========================================`n"

if ($Uninstall) {
    Write-Host "  Removing startup shortcut..." -ForegroundColor Yellow
    if (Test-Path $ShortcutPath) {
        Remove-Item $ShortcutPath -Force
        Write-Host "  Removed: $ShortcutPath" -ForegroundColor Green
    }
    if (Test-Path $VbsPath) {
        Remove-Item $VbsPath -Force
        Write-Host "  Removed: $VbsPath" -ForegroundColor Green
    }
    Write-Host "`n  Uninstalled. Server will no longer start on login.`n" -ForegroundColor Green
    exit 0
}

# 1. Check prerequisites
Write-Host "  [1/4] Checking prerequisites..."
$nodeVersion = & node --version 2>$null
if (-not $nodeVersion) {
    Write-Host "  ERROR: Node.js not found. Install it from https://nodejs.org" -ForegroundColor Red
    exit 1
}
Write-Host "         Node.js $nodeVersion"

# 2. Install dependencies
Write-Host "  [2/4] Installing dependencies..."
Push-Location $ServerDir
& npm install --silent 2>$null
Pop-Location
Push-Location $ClientDir
& npm install --silent 2>$null
Pop-Location
Write-Host "         Done."

# 3. Build server + client for production
Write-Host "  [3/4] Building server + client..."
Push-Location $ServerDir
& npm run build 2>$null
Pop-Location
Push-Location $ClientDir
& npm run build 2>$null
Pop-Location
Write-Host "         Done."

# 4. Create startup script (VBS wrapper runs node hidden, no console window)
Write-Host "  [4/4] Creating Windows startup entry..."

if (-not (Test-Path $VbsDir)) {
    New-Item -ItemType Directory -Path $VbsDir -Force | Out-Null
}

# VBS script that starts the compiled server without a visible console
# window. Runs node against server/dist/index.js (produced in step 3) so
# the launcher path matches the production build artefact, not the tsx
# dev-loop. `--env-file-if-exists=../.env.local` loads the repo-root
# .env.local (network profile etc.) — same as the `npm run dev` script.
# Without it the autostart server would bind differently from the dev
# server (e.g. loopback instead of the Tailscale address) and the UI
# would be unreachable on the address you normally use.
$serverEntryPoint = Join-Path $ServerDir "dist\index.js"
$vbsContent = @"
' Shipwright Command Center — Background Server Launcher
' Auto-generated by install-windows.ps1
Set WshShell = CreateObject("WScript.Shell")
WshShell.CurrentDirectory = "$($ServerDir -replace '\\', '\\')"
WshShell.Run "cmd /c set PORT=$Port && node --env-file-if-exists=../.env.local ""$($serverEntryPoint -replace '\\', '\\')"" > ""%USERPROFILE%\.shipwright-webui\server.log"" 2>&1", 0, False
"@

Set-Content -Path $VbsPath -Value $vbsContent -Encoding ASCII

# Create shortcut in Startup folder
$WScriptShell = New-Object -ComObject WScript.Shell
$Shortcut = $WScriptShell.CreateShortcut($ShortcutPath)
$Shortcut.TargetPath = $VbsPath
$Shortcut.WorkingDirectory = $ServerDir
$Shortcut.Description = "Shipwright Command Center Server"
$Shortcut.Save()

Write-Host "         Startup shortcut: $ShortcutPath"
Write-Host "         Server launcher:  $VbsPath"
Write-Host ""
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  The server will start automatically on next Windows login."
Write-Host "  To start it now:  cd server && node dist/index.js"
Write-Host "  To open the UI:   http://localhost:$Port"
Write-Host "  To uninstall:     .\install-windows.ps1 -Uninstall"
Write-Host ""
