#!/usr/bin/env python3
"""Regenerate `server/src/test/fixtures/launch-payload-strip.json`.

Inputs : a hand-curated set of {description, input} pairs (in this script).
Outputs: the JSON fixture where each pair gains an `expected` field
         computed by `aggregate_triage._strip_control_chars` — the
         CANONICAL Python implementation. The TS port
         `client/src/lib/launchPayload.ts stripControlChars` MUST
         produce byte-equal output for every fixture row.

Reasoning (iterate-2026-05-20-triage-launch-surface-webui review MED #6):
Manual TS implementations of byte-sensitive sanitization drift over
time. Pinning the expected output to a Python-generated fixture means
the parity test fails LOUD when either side drifts. Re-run this script
when `_strip_control_chars` in shipwright changes.

Discovery order mirrors `regen-triage-fixtures.py`.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
# Fixture lives under the CLIENT workspace because that is where the
# consumer (`client/src/lib/launchPayload.ts stripControlChars`) lives
# and the no-cross-package-imports drift-guard (ADR-080) forbids
# server tests from importing client code. The script stays under
# `server/scripts/` because every Python fixture-regen script in this
# repo lives there.
OUT = REPO_ROOT / "client" / "src" / "test" / "fixtures" / "launch-payload-strip.json"


# Hand-curated parity cases. Each row is fed to the canonical Python
# `_strip_control_chars`; the resulting `expected` is pinned into the
# fixture. KEEP these descriptive — they read as a checklist.
CASES: list[dict[str, str]] = [
    {"description": "empty string", "input": ""},
    {"description": "plain ASCII", "input": "/iterate run something"},
    {"description": "preserves newlines", "input": "line1\nline2\nline3"},
    {"description": "preserves tabs", "input": "col1\tcol2\tcol3"},
    {"description": "preserves \\n + \\t together", "input": "a\nb\tc"},
    {"description": "drops bare CR", "input": "line1\rline2"},
    {"description": "drops ASCII BEL (0x07)", "input": "a\x07b"},
    {"description": "drops ASCII ESC (0x1b)", "input": "a\x1bb"},
    {"description": "drops DEL (0x7f)", "input": "a\x7fb"},
    {"description": "preserves multibyte (Umlaut)", "input": "Größe"},
    {"description": "preserves multibyte (emoji)", "input": "fix 🔥 now"},
    {"description": "preserves CJK", "input": "测试"},
    {"description": "drops the full 0x00..0x1F range except \\n, \\t", "input": "".join(chr(c) for c in range(0x00, 0x20))},
    {"description": "control-only payload collapses to empty", "input": "\x07\x1b\x7f"},
    {"description": "whitespace-only stays whitespace", "input": "   \n\t   "},
    {"description": "ANSI color escape sequence (multi-char)", "input": "before\x1b[31mred\x1b[0mafter"},
    {"description": "github-style markdown fences pass through", "input": "```bash\nnpm test\n```"},
    {"description": "long line stays a single line", "input": "x" * 500},
]


def find_aggregate_triage_py() -> Path | None:
    candidates: list[Path] = []
    plugin_root = os.environ.get("SHIPWRIGHT_PLUGIN_ROOT")
    if plugin_root:
        candidates.append(Path(plugin_root).parent / "shared" / "scripts" / "tools" / "aggregate_triage.py")
    home = Path(os.environ.get("HOME") or os.environ.get("USERPROFILE") or "")
    if home:
        candidates.append(
            home / ".claude" / "plugins" / "cache" / "shipwright" / "shared" / "scripts" / "tools" / "aggregate_triage.py"
        )
    candidates.append(REPO_ROOT.parent / "shipwright" / "shared" / "scripts" / "tools" / "aggregate_triage.py")
    for c in candidates:
        if c.exists():
            return c
    return None


def main() -> int:
    src = find_aggregate_triage_py()
    if not src:
        sys.stderr.write(
            "error: shared/scripts/tools/aggregate_triage.py not found. "
            "Set SHIPWRIGHT_PLUGIN_ROOT or place the shipwright monorepo at ../shipwright.\n"
        )
        return 1

    sys.path.insert(0, str(src.parent))
    from aggregate_triage import _strip_control_chars  # noqa: E402

    rows: list[dict[str, str]] = []
    for case in CASES:
        rows.append(
            {
                "description": case["description"],
                "input": case["input"],
                "expected": _strip_control_chars(case["input"]),
            }
        )

    payload = {
        "_comment": (
            "Generated by server/scripts/regen-launch-payload-fixtures.py. "
            "The `expected` field on each row is the byte-equal output of the "
            "CANONICAL Python `_strip_control_chars` (shared/scripts/tools/"
            "aggregate_triage.py). The TS port `client/src/lib/launchPayload.ts"
            " stripControlChars` MUST produce identical output — verified by "
            "client/src/lib/launchPayload.test.ts. Re-run this script when the "
            "canonical implementation changes."
        ),
        "cases": rows,
    }
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    sys.stderr.write(f"wrote {OUT} ({len(rows)} cases)\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
